CREATE TABLE SHIPWRECK(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(2000),
    xCONDITION VARCHAR(255),
    DEPTH INT,
    LATITUDE DECIMAL,
    LONGITUDE DECIMAL,
    YEAR_DISCOVERED INT,
);
/*CREATE TABLE SHIPWRECK(
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(2000),
    CONDITION VARCHAR(255),
    DEPTH INT,
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    YEAR_DISCOVERED INT
); */

